/* JR-Tech Product Database — real images & content from jrtech.com.my */

/* ─── Shared asset sets ─── */
var _MC_BASE  = 'https://jrtech.com.my/wp-content/uploads/2018/04/';
var _MC_B22   = 'https://jrtech.com.my/wp-content/uploads/2022/08/';
var _MC_B22J  = 'https://jrtech.com.my/wp-content/uploads/2022/07/';
var _JN_BASE  = 'https://jrtech.com.my/wp-content/uploads/2022/08/';

var _MC_STEPS = [
  { img: _MC_BASE+'Open-and-Close-the-Lid.jpg',            title:'Open & Close the Lid',      text:'Smart lid control for safe and efficient cooking access during each cycle.' },
  { img: _MC_BASE+'Pour-Oil-and-Water-into-Pan.jpg',        title:'Pour Oil & Water into Pan', text:'Precisely dispenses oil and liquid — the machine monitors quantities automatically.' },
  { img: _MC_BASE+'Accurate-Temperature-For-Heating.jpg',   title:'Accurate Temperature',      text:'AI-controlled heating maintains the exact temperature required for every dish.' },
  { img: _MC_BASE+'Stir-Up-Turn-Over.jpg',                  title:'Stir & Turn Over',          text:'The automated stirring arm replicates professional wok-toss technique at scale.' },
  { img: _MC_BASE+'Reading-Recipe.jpg',                     title:'Recipe Reading',            text:'Load recipes via IC card or mobile app — the machine follows every step automatically.' },
  { img: _MC_BASE+'Food.jpg',                               title:'Consistent Results',        text:'Every dish comes out perfectly every time, without relying on chef skill or experience.' },
  { img: _MC_BASE+'Seasoning.jpg',                          title:'Auto Seasoning',            text:'Seasoning is added at exactly the right moment in the cooking cycle.' },
  { img: _MC_BASE+'Alarm.jpg',                              title:'Smart Alerts',              text:'The machine alerts you when food is ready or if any issue needs attention.' }
];

var _MC_DESC = [
  { title:'Fully Self-Controlled',      text:'Save recipes on an IC card or on your mobile phone application, and connect with the machine — once the machine receives recipes via IC card or mobile phone application, it works automatically.' },
  { title:'Easy Operation',             text:'It is not only easy and convenient for customers to operate but also high-producing. One person can operate 5–6 machines at the same time.' },
  { title:'Less Time Required',         text:'Less than 4 minutes for cooking each dish — time-saving and efficient for high-volume service.' },
  { title:'Standardization of Taste',   text:'Follow the application steps for standard procedures for each dish. Every portion tastes the same, every service.' },
  { title:'Private Recipes',            text:'Create an account on the application and edit any recipes you want. Your recipes stay private and are stored securely in the cloud.' },
  { title:'High Adaptability',          text:'Free to adjust the cooking temperature and control the speed of frying. The machine adapts to your menu, not the other way around.' }
];

var _JNOX_FEAT = [
  'High efficiency, low noise, no pollution',
  'National patent coil — more uniform firepower',
  'PCB box with fully sealed design',
  'Handle-type magnetic switch — 8 gear firepower control',
  'Triple three-dimensional radiation shielding design',
  'Advanced Germany Infineon IGBT Technology',
  'IPX6 protection level — multiple safety layers'
];

var _JNOX_ACC = [
  { src: _JN_BASE+'Custom-Flat-Basket.png',                   name: 'Custom Flat Basket' },
  { src: _JN_BASE+'Freestanding-Pasta-Basket.png',            name: 'Freestanding Pasta Basket' },
  { src: _JN_BASE+'Desktop-Fryer-Basket.png',                 name: 'Desktop Fryer Basket' },
  { src: _JN_BASE+'Desktop-Fryer-Basket-1.png',               name: 'Desktop Fryer Basket' },
  { src: _JN_BASE+'Freestanding-Fryer-Basket.png',            name: 'Freestanding Fryer Basket' },
  { src: _JN_BASE+'High-grade-Soup-Valve.png',                name: 'High-grade Soup Valve' },
  { src: _JN_BASE+'Oil-Drain-Valve.png',                      name: 'Oil Drain Valve' },
  { src: _JN_BASE+'Two-Rings-Iron-Wok.png',                   name: 'Two Rings Iron Wok' },
  { src: _JN_BASE+'Composite-Bottom-Stainless-Steel-Pot.png', name: 'Composite Bottom Stainless Steel Pot' }
];

var JRT_PRODUCTS = [

  /* ══════════════════ MegCook ══════════════════ */
  { id:'C35PB01', brand:'MegCook', slug:'megcook', name:'C35PB01',
    cat:'Automatic Cooking Machine', tag:'Compact',
    imgs:[
      _MC_B22+'c35pb01-c04_1_-600x491.jpg',
      _MC_B22+'c35pb01-c04-600x479.png',
      _MC_B22+'Super-Power-Super-Flavour.jpg',
      _MC_B22+'Cloud-Menu-App.jpg',
      _MC_B22+'AI-Recipe.jpg',
      _MC_B22+'Touchscreen.jpg',
      _MC_B22+'Restaurant.jpg',
      _MC_B22+'Fast-Food.jpg',
      _MC_B22+'Dining-Hall.jpg'
    ],
    img: _MC_B22+'c35pb01-c04_1_-600x491.jpg',
    tagline:'One machine, one operator, up to 300 meals per day — save labour and standardise taste.',
    features:[
      'Better Life Spend Motor, Full Power',
      'Elite Crystallite — cleaning-friendly surface',
      '304 Stainless Steel, durable & hygienic',
      'Detachable design for easy maintenance',
      'Heightened lid — easier ingredient loading',
      'Anti-fire protection with alarm system',
      'Fully self-controlled via IC card or mobile app'
    ],
    steps: _MC_STEPS,
    descBlocks: _MC_DESC,
    specs:{
      'Working Voltage':'220 V – 240 V',
      'Power':'3520 W',
      'Product Size (W × D × H)':'500 × 545 × 325 mm (closed) / 500 × 545 × 525 mm (open)',
      'Panel':'Special Glass-Ceramic + Stainless Steel',
      'Style':'Countertop',
      'Colour':'Silver',
      'Net Weight':'18 kg',
      'Certification':'CE / HACCP'
    },
    uses:['Hotel kitchens','Hospital cafeterias','Factory canteens','Chain restaurants'] },

  { id:'C44PB01', brand:'MegCook', slug:'megcook', name:'C44PB01',
    cat:'Automatic Cooking Machine', tag:'High Capacity',
    imgs:[
      _MC_B22+'C44PA01-C01-600x814.jpeg',
      _MC_B22+'C44PA01-C01.jpeg',
      _MC_B22+'Super-Power-Super-Flavour.jpg',
      _MC_B22+'Cloud-Menu-App.jpg',
      _MC_B22+'AI-Recipe.jpg',
      _MC_B22+'Touchscreen.jpg'
    ],
    img: _MC_B22+'C44PA01-C01-600x814.jpeg',
    tagline:'Scaled-up cooking capacity with the same intelligent automation — ideal for 200+ cover operations.',
    features:[
      'Better Life Spend Motor, Full Power',
      'Elite Crystallite — cleaning-friendly surface',
      '304 Stainless Steel, durable & hygienic',
      'More adjuncts if repair is needed',
      'Heightened lid — easier to cook',
      'Anti-fire — better protection',
      'Detachable design for cleaning',
      'Can serve 300+ meals per day',
      'ROI within 3 months',
      'Reduces manpower requirements',
      'User-friendly touchscreen interface'
    ],
    steps: _MC_STEPS,
    descBlocks: _MC_DESC,
    specs:{
      'Working Voltage':'220 V – 240 V',
      'Power':'3520 W',
      'Product Size (W × D × H)':'500 × 545 × 325 mm (closed) / 500 × 545 × 525 mm (open)',
      'Panel':'Special Glass-Ceramic + Stainless Steel',
      'Certification':'CE / HACCP'
    },
    uses:['Corporate cafeterias','Hospital kitchens','School canteens','High-volume restaurants'] },

  { id:'3520W-CE', brand:'MegCook', slug:'megcook', name:'Cooking Machine (3520W-CE)',
    cat:'Robot Chef', tag:'CE Certified',
    imgs:[
      'https://jrtech.com.my/wp-content/uploads/2018/04/3520W-CE-600x771.jpg',
      'https://jrtech.com.my/wp-content/uploads/2018/04/3520W-CE-1-600x771.jpg',
      'https://jrtech.com.my/wp-content/uploads/2018/04/1614696700914925.png',
      'https://jrtech.com.my/wp-content/uploads/2018/04/1614696868409735.png',
      'https://jrtech.com.my/wp-content/uploads/2018/04/1614697236488605.png',
      'https://jrtech.com.my/wp-content/uploads/2018/04/1614697296520085.png',
      'https://jrtech.com.my/wp-content/uploads/2018/04/1614777124826999.png',
      'https://jrtech.com.my/wp-content/uploads/2018/04/1614261292623444.png'
    ],
    img:'https://jrtech.com.my/wp-content/uploads/2018/04/3520W-CE-600x771.jpg',
    tagline:'CE-certified robot chef with dual-pump, 4-cartridge automatic liquid filling — fully automated cooking from start to finish.',
    features:[
      'Motor with long lifespan and high motivation',
      '3520 W super power — speedy cooking',
      'Upgraded lid with large capacity pan',
      'Micro-crystal surface — easy and convenient to clean',
      'Anti-fire misoperation alarm programme',
      '304 stainless steel — durable and sturdy case',
      'Detachable design for better maintenance',
      'Attachable automatic liquid filling system'
    ],
    steps: _MC_STEPS,
    descBlocks: _MC_DESC,
    specs:{
      'Rated Power':'3520 W',
      'Style':'Countertop',
      'Stove':'Single',
      'Product Number':'C35PB01-C04',
      'Item Number':'MEG1F.12S',
      'Machine Name':'Robot M1',
      'Colour':'Silver',
      'Material':'Glass-ceramic + SUS304',
      'Product Dimensions (L × W × H)':'500 × 545 × 325 mm (closed) / 500 × 545 × 525 mm (open)',
      'Net Weight':'18 kg',
      'Gross Weight':'22 kg',
      'Package Dimensions':'700 × 620 × 380 mm',
      'Remarks':'CE certified (Dual pump, 4 cartridges)'
    },
    uses:['Cloud kitchens','Hotel central production','Airline catering','Stadium F&B'] },

  { id:'3520W', brand:'MegCook', slug:'megcook', name:'Cooking Machine (3520W)',
    cat:'Robot Chef', tag:'Flagship',
    imgs:[
      _MC_B22J+'3520W-1-600x771.jpg',
      _MC_B22J+'3520W-2-600x771.jpg',
      _MC_B22J+'1614696700914925-1.png',
      _MC_B22J+'1614696868409735-1.png',
      _MC_B22J+'1614697226510517-1.png',
      _MC_B22J+'1614697236488605-1.png',
      _MC_B22J+'1614697296520085-1.png',
      _MC_BASE+'1614777124826999.png',
      _MC_BASE+'1614261292623444.png'
    ],
    img: _MC_B22J+'3520W-1-600x771.jpg',
    tagline:'The flagship MegCook robot chef — 3520 W superpower, compact design, runs multiple units simultaneously with one operator.',
    features:[
      '3520 W superpower, speedy cooking cycle',
      'Manually add food and seasoning — fully automatic stir-fry',
      'Compact design — multiple machines running simultaneously',
      'Long life motor, full power output',
      'Download the cloud menu app — access thousands of recipes',
      'Attachable automatic liquid filling system'
    ],
    steps: _MC_STEPS,
    descBlocks: _MC_DESC,
    specs:{
      'Rated Power':'3520 W',
      'Style':'Countertop',
      'Stove':'Single',
      'Product Number':'C35PA01-C01',
      'Item Number':'MEG1M.20S',
      'Machine Name':'Smart Cooking Machine M1',
      'Colour':'Silver',
      'Material':'Glass-ceramic + SUS304',
      'Product Dimensions (L × W × H)':'500 × 585 × 355 mm (closed) / 500 × 585 × 555 mm (open)',
      'Net Weight':'13.5 kg',
      'Gross Weight':'16 kg',
      'Package':'650 × 440 × 370 mm'
    },
    uses:['Hotel central kitchens','Large canteens','Food production facilities','Restaurant groups'] },

  /* ══════════════════ J-Nox ══════════════════ */
  { id:'LT-B300IV-B105', brand:'J-Nox', slug:'jnox', name:'LT-B300IV-B105',
    cat:'Freestanding 4-Burner Induction', tag:'4-Zone',
    imgs:[ _JN_BASE+'7-Freestanding-Induction-Four-Burners-600x600.jpg',
           _JN_BASE+'7-Freestanding-Induction-Four-Burners.jpg' ],
    img:   _JN_BASE+'7-Freestanding-Induction-Four-Burners-600x600.jpg',
    tagline:'Four independent 5 kW induction zones in one freestanding unit — energy-efficient, zero open flame.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'700 × 800 × 800+150', 'Power (kW)':'4 × 5', 'Total Power (kW)':'20',
            'Voltage (V)':'380', 'Frequency (Hz)':'50', 'Glass Size (mm)':'Ø300' },
    uses:['Hotel kitchens','Hospital F&B','Factory canteens','Restaurants'] },

  { id:'LT-B300IV-B135', brand:'J-Nox', slug:'jnox', name:'LT-B300IV-B135',
    cat:'Freestanding 4-Burner Induction', tag:'High Power',
    imgs:[ _JN_BASE+'7-Freestanding-Induction-Four-Burners-600x600.jpg',
           _JN_BASE+'7-Freestanding-Induction-Four-Burners.jpg' ],
    img:   _JN_BASE+'7-Freestanding-Induction-Four-Burners-600x600.jpg',
    tagline:'Four high-power 13.5 kW zones — gas-intensity induction for the most demanding wok stations.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'700 × 800 × 800+150', 'Power (kW)':'4 × 13.5', 'Total Power (kW)':'54',
            'Voltage (V)':'380', 'Frequency (Hz)':'50', 'Glass Size (mm)':'Ø300' },
    uses:['High-volume restaurants','Stadium kitchens','Central production kitchens'] },

  { id:'LT-B300VI-B105', brand:'J-Nox', slug:'jnox', name:'LT-B300VI-B105',
    cat:'Freestanding 6-Burner Induction', tag:'6-Zone',
    imgs:[ _JN_BASE+'8-Freestanding-Induction-Six-Burners-600x600.jpg',
           _JN_BASE+'8-Freestanding-Induction-Six-Burners.jpg' ],
    img:   _JN_BASE+'8-Freestanding-Induction-Six-Burners-600x600.jpg',
    tagline:'Six simultaneous induction cooking zones — maximum output per square metre, zero gas line required.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'1050 × 800 × 800+150', 'Power (kW)':'6 × 5', 'Total Power (kW)':'30',
            'Voltage (V)':'380', 'Frequency (Hz)':'50', 'Glass Size (mm)':'Ø300' },
    uses:['Hotel all-day-dining kitchens','Hospital F&B','Corporate cafeterias'] },

  { id:'LT-B300VI-B135', brand:'J-Nox', slug:'jnox', name:'LT-B300VI-B135',
    cat:'Freestanding 6-Burner Induction', tag:'Max Power',
    imgs:[ _JN_BASE+'8-Freestanding-Induction-Six-Burners-600x600.jpg',
           _JN_BASE+'8-Freestanding-Induction-Six-Burners.jpg' ],
    img:   _JN_BASE+'8-Freestanding-Induction-Six-Burners-600x600.jpg',
    tagline:'Six zones at 13.5 kW each — matches the intensity of the strongest gas burners without combustion.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'1050 × 800 × 800+150', 'Power (kW)':'6 × 13.5', 'Total Power (kW)':'81',
            'Voltage (V)':'380', 'Frequency (Hz)':'50', 'Glass Size (mm)':'Ø300' },
    uses:['Hotel central kitchens','Airline catering','Stadium concessions'] },

  { id:'LT-CCJ200-BS105', brand:'J-Nox', slug:'jnox', name:'LT-CCJ200-BS105',
    cat:'Tabletop Auto Cooking Machine', tag:'Entry-Level',
    imgs:[ _JN_BASE+'3-Tabletop-Automatic-Cooking-Machine-1-600x600.jpg',
           _JN_BASE+'3-Tabletop-Automatic-Cooking-Machine-1.jpg' ],
    img:   _JN_BASE+'3-Tabletop-Automatic-Cooking-Machine-1-600x600.jpg',
    tagline:'Compact 200-series tabletop cooker — automatic stirring and induction heating in a counter-top footprint.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'525 × 475 × 530', 'Power (kW)':'3.5 – 5', 'Voltage (V)':'220',
            'Frequency (Hz)':'50', 'Max Capacity (kg)':'0.2 – 1.5' },
    uses:['Small restaurants','Café kitchens','Hospital wards','Office pantries'] },

  { id:'LT-CCJ300-BA105', brand:'J-Nox', slug:'jnox', name:'LT-CCJ300-BA105',
    cat:'Tabletop Auto Cooking Machine', tag:'Versatile',
    imgs:[ _JN_BASE+'2-Tabletop-Automatic-Cooking-Machine-1-600x600.jpg',
           _JN_BASE+'2-Tabletop-Automatic-Cooking-Machine-1.jpg' ],
    img:   _JN_BASE+'2-Tabletop-Automatic-Cooking-Machine-1-600x600.jpg',
    tagline:'BA-type bowl optimised for braising, soups and sauces — consistent gentle cooking at scale.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'720 × 500 × 680', 'Power (kW)':'5', 'Voltage (V)':'220',
            'Frequency (Hz)':'50', 'Max Capacity (kg)':'2 – 3' },
    uses:['Hotel banquet kitchens','Catering companies','School canteens','Hospital kitchens'] },

  { id:'LT-CCJ300-BA205', brand:'J-Nox', slug:'jnox', name:'LT-CCJ300-BA205',
    cat:'Tabletop Auto Cooking Machine', tag:'Extended Run',
    imgs:[ _JN_BASE+'2-Tabletop-Automatic-Cooking-Machine-1-600x600.jpg',
           _JN_BASE+'2-Tabletop-Automatic-Cooking-Machine-1.jpg' ],
    img:   _JN_BASE+'2-Tabletop-Automatic-Cooking-Machine-1-600x600.jpg',
    tagline:'Extended cooking cycle for all-day simmering — curries, stocks and slow-cooked dishes at volume.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'720 × 500 × 680', 'Power (kW)':'5', 'Voltage (V)':'220',
            'Frequency (Hz)':'50', 'Max Capacity (kg)':'2 – 3' },
    uses:['Hotel kitchens','Curry & sauce production','Institutional catering','Food manufacturing'] },

  { id:'LT-CCJ300-BC105', brand:'J-Nox', slug:'jnox', name:'LT-CCJ300-BC105',
    cat:'Intelligent Stir Fryer', tag:"Chef's Choice",
    imgs:[ _JN_BASE+'4-Intelligent-Stir-Fryer-Cooking-Machine-1-600x600.jpg',
           _JN_BASE+'4-Intelligent-Stir-Fryer-Cooking-Machine-1.jpg' ],
    img:   _JN_BASE+'4-Intelligent-Stir-Fryer-Cooking-Machine-1-600x600.jpg',
    tagline:'350 RPM wok-toss mechanism — replicates skilled-chef stir-fry technique at commercial scale.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'580 × 500 × 550', 'Power (kW)':'5', 'Voltage (V)':'220',
            'Frequency (Hz)':'50', 'Max Capacity (kg)':'0.5 – 3.5' },
    uses:['Chinese restaurants','Hotel wok stations','Hawker-style canteens','Fast food production'] },

  { id:'LT-CCJ300-BS105', brand:'J-Nox', slug:'jnox', name:'LT-CCJ300-BS105',
    cat:'Tabletop Auto Cooking Machine', tag:'Standard',
    imgs:[ _JN_BASE+'3-Tabletop-Automatic-Cooking-Machine-1-600x600.jpg',
           _JN_BASE+'3-Tabletop-Automatic-Cooking-Machine-1.jpg' ],
    img:   _JN_BASE+'3-Tabletop-Automatic-Cooking-Machine-1-600x600.jpg',
    tagline:'Most popular 300-series — versatile BS stirring suits the widest range of dish types.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'630 × 500 × 550', 'Power (kW)':'5', 'Voltage (V)':'220',
            'Frequency (Hz)':'50', 'Max Capacity (kg)':'0.5 – 3.5' },
    uses:['Restaurants','Cafeteria kitchens','Hotel staff canteens','Catering operations'] },

  { id:'LT-CCJ300-ZA205', brand:'J-Nox', slug:'jnox', name:'LT-CCJ300-ZA205',
    cat:'Tabletop Auto Cooking Machine', tag:'High Moisture',
    imgs:[ _JN_BASE+'2-Tabletop-Automatic-Cooking-Machine-1-600x600.jpg',
           _JN_BASE+'2-Tabletop-Automatic-Cooking-Machine-1.jpg' ],
    img:   _JN_BASE+'2-Tabletop-Automatic-Cooking-Machine-1-600x600.jpg',
    tagline:'ZA bowl optimised for high-moisture dishes — soups, braises and stews with fast batch recovery.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'720 × 500 × 750', 'Power (kW)':'5', 'Voltage (V)':'220',
            'Frequency (Hz)':'50', 'Max Capacity (kg)':'2 – 3' },
    uses:['Hotel banquet production','Large cafeterias','Central kitchens'] },

  { id:'LT-CCJ300-ZB105', brand:'J-Nox', slug:'jnox', name:'LT-CCJ300-ZB105',
    cat:'Freestanding Auto Cooking Machine', tag:'Freestanding',
    imgs:[ _JN_BASE+'5-Freestanding-Automatic-Cooking-Machine-1-600x600.jpg',
           _JN_BASE+'5-Freestanding-Automatic-Cooking-Machine-1.jpg' ],
    img:   _JN_BASE+'5-Freestanding-Automatic-Cooking-Machine-1-600x600.jpg',
    tagline:'Floor-standing auto cooker — integrates under service counters and alongside conventional cooking lines.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'740 × 720 × 1350', 'Power (kW)':'5', 'Voltage (V)':'220',
            'Frequency (Hz)':'50', 'Max Capacity (kg)':'2 – 3' },
    uses:['Open kitchens','Space-constrained cafeterias','Kiosk operations'] },

  { id:'LT-CCJ360-BC105', brand:'J-Nox', slug:'jnox', name:'LT-CCJ360-BC105',
    cat:'Intelligent Stir Fryer', tag:'360-Series',
    imgs:[ _JN_BASE+'4-Intelligent-Stir-Fryer-Cooking-Machine-1-600x600.jpg',
           _JN_BASE+'4-Intelligent-Stir-Fryer-Cooking-Machine-1.jpg' ],
    img:   _JN_BASE+'4-Intelligent-Stir-Fryer-Cooking-Machine-1-600x600.jpg',
    tagline:'Enlarged 360-series wok with full-coverage stirring — every ingredient evenly cooked.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'640 × 560 × 710', 'Power (kW)':'5', 'Voltage (V)':'220',
            'Frequency (Hz)':'50', 'Max Capacity (kg)':'1 – 5' },
    uses:['Wok-specialist restaurants','Hotel Chinese kitchens','Stadium food concessions'] },

  { id:'LT-CCJ360-BS105', brand:'J-Nox', slug:'jnox', name:'LT-CCJ360-BS105',
    cat:'Tabletop Auto Cooking Machine', tag:'360-Series',
    imgs:[ _JN_BASE+'3-Tabletop-Automatic-Cooking-Machine-1-600x600.jpg',
           _JN_BASE+'3-Tabletop-Automatic-Cooking-Machine-1.jpg' ],
    img:   _JN_BASE+'3-Tabletop-Automatic-Cooking-Machine-1-600x600.jpg',
    tagline:'360-series wide bowl — full-coverage stirring ensures edges cook as evenly as the centre.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'630 × 560 × 710', 'Power (kW)':'5', 'Voltage (V)':'220',
            'Frequency (Hz)':'50', 'Max Capacity (kg)':'1 – 5' },
    uses:['Medium restaurants','Institutional catering','Hotel staff dining'] },

  { id:'LT-CCJ600-ZA225', brand:'J-Nox', slug:'jnox', name:'LT-CCJ600-ZA225',
    cat:'Large Auto Cooking Machine', tag:'Large Scale',
    imgs:[ _JN_BASE+'1-Automatic-Cooking-Machine-1-600x600.jpg',
           _JN_BASE+'1-Automatic-Cooking-Machine-1.jpg' ],
    img:   _JN_BASE+'1-Automatic-Cooking-Machine-1-600x600.jpg',
    tagline:'600-series large-batch production — 25 kW, 20 kg capacity, 50+ servings per cycle.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'1470 × 1185 × 1570', 'Power (kW)':'25', 'Voltage (V)':'380',
            'Frequency (Hz)':'50', 'Max Capacity (kg)':'20' },
    uses:['Central production kitchens','Hospital mass catering','School bulk cooking','Food manufacturers'] },

  { id:'LT-CCJ600-ZB225', brand:'J-Nox', slug:'jnox', name:'LT-CCJ600-ZB225',
    cat:'Large Auto Cooking Machine', tag:'Industrial',
    imgs:[ _JN_BASE+'1-Automatic-Cooking-Machine-1-600x600.jpg',
           _JN_BASE+'1-Automatic-Cooking-Machine-1.jpg' ],
    img:   _JN_BASE+'1-Automatic-Cooking-Machine-1-600x600.jpg',
    tagline:'ZB configuration for dense/dry large-batch dishes — fried rice and noodles at industrial scale.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'1470 × 1185 × 1570', 'Power (kW)':'25', 'Voltage (V)':'380',
            'Frequency (Hz)':'50', 'Max Capacity (kg)':'20' },
    uses:['Central canteen kitchens','Industrial F&B production','Armed forces catering'] },

  { id:'LT-D1000-E130', brand:'J-Nox', slug:'jnox', name:'LT-D1000-E130',
    cat:'Single Wok Induction Cooker', tag:'Single Wok',
    imgs:[ _JN_BASE+'6-Freestanding-Induction-Single-Larger-Wok-Cooker-600x600.jpg',
           _JN_BASE+'6-Freestanding-Induction-Single-Larger-Wok-Cooker.jpg' ],
    img:   _JN_BASE+'6-Freestanding-Induction-Single-Larger-Wok-Cooker-600x600.jpg',
    tagline:'Direct gas-burner replacement — 30 kW induction for the largest commercial woks, 105 L capacity.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'1200 × 1300 × 800+400', 'Power (kW)':'30', 'Voltage (V)':'380',
            'Frequency (Hz)':'50/60', 'Capacity (L)':'105' },
    uses:['Chinese restaurants','Wok stations','Hotel kitchens','Catering companies'] },

  { id:'LT-D1000II-E130', brand:'J-Nox', slug:'jnox', name:'LT-D1000II-E130',
    cat:'Double Wok Induction Cooker', tag:'Twin Wok',
    imgs:[ _JN_BASE+'7-Freestanding-Induction-Double-Larger-Wok-Cooker-600x600.jpg',
           _JN_BASE+'7-Freestanding-Induction-Double-Larger-Wok-Cooker.jpg' ],
    img:   _JN_BASE+'7-Freestanding-Induction-Double-Larger-Wok-Cooker-600x600.jpg',
    tagline:'Two 30 kW zones in one unit — doubles wok throughput with the same electrical connection.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'2400 × 1300 × 800+400', 'Power (kW)':'2 × 30', 'Total Power (kW)':'60',
            'Voltage (V)':'380', 'Frequency (Hz)':'50', 'Capacity (L)':'2 × 105' },
    uses:['High-volume Chinese kitchens','Hotel banquet wok stations','Hawker-style canteens'] },

  { id:'LT-D1200-E130', brand:'J-Nox', slug:'jnox', name:'LT-D1200-E130 / E135 / E145',
    cat:'Single Wok Induction Cooker', tag:'Multi-Spec',
    imgs:[ _JN_BASE+'6-Freestanding-Induction-Single-Larger-Wok-Cooker-600x600.jpg',
           _JN_BASE+'6-Freestanding-Induction-Single-Larger-Wok-Cooker.jpg' ],
    img:   _JN_BASE+'6-Freestanding-Induction-Single-Larger-Wok-Cooker-600x600.jpg',
    tagline:'Three power specs for the 1200-series — 30–40 kW for large woks up to 180 L capacity.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'1400 × 1500 × 800+400', 'Power (kW)':'30 – 40', 'Voltage (V)':'380',
            'Frequency (Hz)':'50/60', 'Capacity (L)':'180' },
    uses:['Wok-focused restaurants','Hotel production kitchens','Large canteen kitchens'] },

  { id:'LT-D1200II-E130', brand:'J-Nox', slug:'jnox', name:'LT-D1200II-E130 / E135',
    cat:'Double Wok Induction Cooker', tag:'Twin High-Power',
    imgs:[ _JN_BASE+'7-Freestanding-Induction-Double-Larger-Wok-Cooker-600x600.jpg',
           _JN_BASE+'7-Freestanding-Induction-Double-Larger-Wok-Cooker.jpg' ],
    img:   _JN_BASE+'7-Freestanding-Induction-Double-Larger-Wok-Cooker-600x600.jpg',
    tagline:'Two high-power zones in the 1200-series frame — replaces two gas wok burners in a single unit.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'2800 × 1500 × 800+400', 'Power (kW)':'2 × 30 – 40', 'Voltage (V)':'380',
            'Frequency (Hz)':'50/60', 'Capacity (L)':'2 × 180' },
    uses:['High-output wok kitchens','Hotel F&B','Central production kitchens'] },

  { id:'LT-D550-E108', brand:'J-Nox', slug:'jnox', name:'LT-D550-E108 / E112 / E115',
    cat:'Single Wok Induction Cooker', tag:'Mid-Range',
    imgs:[ _JN_BASE+'6-Freestanding-Induction-Single-Larger-Wok-Cooker-600x600.jpg',
           _JN_BASE+'6-Freestanding-Induction-Single-Larger-Wok-Cooker.jpg' ],
    img:   _JN_BASE+'6-Freestanding-Induction-Single-Larger-Wok-Cooker-600x600.jpg',
    tagline:'Compact 550-series in three power options — the right induction wok burner for smaller operations.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Power Options (kW)':'10.8 / 11.2 / 11.5', 'Wok Size':'45 – 55 cm diameter',
            'Voltage (V)':'380', 'Frequency (Hz)':'50', 'Certification':'CE' },
    uses:['Small restaurants','Café kitchens','Food court stalls','Hotel room-service kitchens'] },

  { id:'LT-D550II-E108', brand:'J-Nox', slug:'jnox', name:'LT-D550II-E108 / E112 / E115',
    cat:'Double Wok Induction Cooker', tag:'Compact Twin',
    imgs:[ _JN_BASE+'7-Freestanding-Induction-Double-Larger-Wok-Cooker-600x600.jpg',
           _JN_BASE+'7-Freestanding-Induction-Double-Larger-Wok-Cooker.jpg' ],
    img:   _JN_BASE+'7-Freestanding-Induction-Double-Larger-Wok-Cooker-600x600.jpg',
    tagline:'Two compact induction wok zones in the 550-series frame — ideal for open kitchens and food courts.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Power per Zone (kW)':'10.8 / 11.2 / 11.5', 'Wok Size':'45 – 55 cm diameter',
            'Voltage (V)':'380', 'Frequency (Hz)':'50', 'Certification':'CE' },
    uses:['Open kitchens','Food courts','Small restaurants','Hotel display cooking'] },

  { id:'LT-D600-E112', brand:'J-Nox', slug:'jnox', name:'LT-D600-E112',
    cat:'Single Wok Induction Cooker', tag:'Standard',
    imgs:[ _JN_BASE+'6-Freestanding-Induction-Single-Larger-Wok-Cooker-600x600.jpg',
           _JN_BASE+'6-Freestanding-Induction-Single-Larger-Wok-Cooker.jpg' ],
    img:   _JN_BASE+'6-Freestanding-Induction-Single-Larger-Wok-Cooker-600x600.jpg',
    tagline:'Mid-range 600-series workhorse — 11.2 kW balancing power and energy for most existing kitchens.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'Approx. 800 × 900 × 800+350', 'Power (kW)':'11.2',
            'Wok Size':'50 – 60 cm', 'Voltage (V)':'380', 'Frequency (Hz)':'50', 'Certification':'CE' },
    uses:['Mid-size restaurants','Hotel staff canteens','Catering companies'] },

  { id:'LT-D600II-E112', brand:'J-Nox', slug:'jnox', name:'LT-D600II-E112',
    cat:'Double Wok Induction Cooker', tag:'Twin Standard',
    imgs:[ _JN_BASE+'7-Freestanding-Induction-Double-Larger-Wok-Cooker-600x600.jpg',
           _JN_BASE+'7-Freestanding-Induction-Double-Larger-Wok-Cooker.jpg' ],
    img:   _JN_BASE+'7-Freestanding-Induction-Double-Larger-Wok-Cooker-600x600.jpg',
    tagline:'Two 11.2 kW zones from one unit — fewer electrical connections, more wok output per station.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Power per Zone (kW)':'11.2', 'Total Power (kW)':'22.4', 'Wok Size':'50 – 60 cm',
            'Voltage (V)':'380', 'Frequency (Hz)':'50', 'Certification':'CE' },
    uses:['Mid-to-high-volume restaurants','Hotel banquet kitchens','Corporate cafeterias'] },

  { id:'LT-D700-E115', brand:'J-Nox', slug:'jnox', name:'LT-D700-E115',
    cat:'Single Wok Induction Cooker', tag:'Wide Frame',
    imgs:[ _JN_BASE+'6-Freestanding-Induction-Single-Larger-Wok-Cooker-600x600.jpg',
           _JN_BASE+'6-Freestanding-Induction-Single-Larger-Wok-Cooker.jpg' ],
    img:   _JN_BASE+'6-Freestanding-Induction-Single-Larger-Wok-Cooker-600x600.jpg',
    tagline:'Wide 700-series burner coil — even heat across the largest 60–70 cm commercial wok bases.',
    features: _JNOX_FEAT, descEyebrow:'Compatible Accessories', extraImgs: _JNOX_ACC,
    specs:{ 'Size (L × W × H) mm':'Approx. 900 × 1000 × 800+350', 'Power (kW)':'11.5',
            'Wok Size':'60 – 70 cm', 'Voltage (V)':'380', 'Frequency (Hz)':'50', 'Certification':'CE' },
    uses:['Large wok kitchens','Hotel signature restaurants','High-volume Chinese F&B'] },

  /* ══════════════════ JR-Chem ══════════════════ */
  { id:'Utensil-Washer', brand:'JR-Chem', slug:'jrchem', name:'Utensil Washer',
    cat:'Industrial Utensil Washer', tag:'Industrial',
    imgs:[ _JN_BASE+'11-VT-F21DM-1-600x270.jpg', _JN_BASE+'11-VT-F21DM-1.jpg' ],
    img:  _JN_BASE+'11-VT-F21DM-1-600x270.jpg',
    tagline:'Industrial high-pressure washing for large pots, trays and cookware — Italian pump technology.',
    features:[
      'High-pressure wash & rinse for large cookware',
      'Italian imported wash pump technology',
      'HACCP-compliant auto-dose chemical system',
      'SUS304 full stainless steel construction',
      'Anti-rat design — hygienic and durable',
      'Available for rental or purchase'
    ],
    specs:{ 'Type':'Industrial Utensil Washer', 'Material':'SUS304 Stainless Steel',
            'Chemical Dosing':'Auto HACCP dose', 'Power Supply':'380 V / 50 Hz / 3-phase',
            'Pump':'Italian technology' },
    uses:['Hotel central kitchens','Hospital kitchen facilities','Large canteen operations','Catering companies'] },

  { id:'VT-1', brand:'JR-Chem', slug:'jrchem', name:'VT-1 Door Type with Work Station',
    cat:'Door Type Dishwasher', tag:'With Station',
    imgs:[ _JN_BASE+'VT-1-Door-Type-with-work-station-600x599.jpg',
           _JN_BASE+'VT-1-Door-Type-with-work-station.jpg' ],
    img:  _JN_BASE+'VT-1-Door-Type-with-work-station-600x599.jpg',
    tagline:'Complete warewashing station — door-type dishwasher with integrated in-feed and out-feed work station.',
    features:[
      'Door type design with integrated work station',
      'Italian imported wash & rinse pumps',
      'HACCP-compliant auto-dose chemical system',
      'SUS304 full stainless steel construction with anti-rat design',
      'Reliable mechanical control panel — easy to maintain',
      'Low maintenance cost',
      'Available for rental or purchase'
    ],
    specs:{ 'Dimension':'697 × 686 × 1578 mm', 'Loading Height':'420 mm',
            'Cycle Time':'60 / 90 / 180 sec', 'Capacity':'60 racks/hr', 'Rinse Usage':'3 L/rack',
            'Wash Pump Power':'0.75 kW', 'Wash Tank Heater':'3 kW', 'Booster Heater':'14 kW',
            'Electric Loading':'18 kW', 'Power Supply':'380 V / 50 Hz / 3-phase', 'Net Weight':'125 kg' },
    uses:['Hotel F&B outlets','Hospital kitchens','Mid-size restaurants','Factory canteens'] },

  { id:'VT-3', brand:'JR-Chem', slug:'jrchem', name:'VT-3',
    cat:'Commercial Dishwasher', tag:'Compact',
    imgs:[ _JN_BASE+'VT-3-600x599.jpg', _JN_BASE+'VT-3.jpg', _JN_BASE+'VT3-Plan.jpg' ],
    img:  _JN_BASE+'VT-3-600x599.jpg',
    tagline:'Compact commercial dishwasher with 60 racks per hour throughput — HACCP compliant, Italian pump.',
    features:[
      'New design wash arm & rinse arm for great cleaning effects',
      'Italian imported wash pump and rinse pump',
      'Reliable mechanical branded control panel',
      'SUS304 stainless steel construction with anti-rat design',
      'Low maintenance cost and easy to service',
      'Available for rental or purchase'
    ],
    specs:{ 'Dimension':'697 × 686 × 1578 mm', 'Loading Height':'420 mm',
            'Cycle Time':'60 / 90 / 180 sec', 'Capacity':'60 racks/hr', 'Rinse Usage':'3 L/rack',
            'Wash Pump Power':'0.75 kW', 'Wash Tank Heater':'3 kW', 'Booster Heater':'14 kW',
            'Rinse Pump Power':'0.25 kW', 'Electric Loading':'18 kW',
            'Power Supply':'380 V / 50 Hz / 3-phase', 'Net Weight':'125 kg' },
    uses:['Small restaurants','Cafés','Office pantries','Food court stalls'] },

  { id:'VTF11DM', brand:'JR-Chem', slug:'jrchem', name:'VTF11DM',
    cat:'Mini Flight Dishwasher', tag:'Mini Flight',
    imgs:[ _JN_BASE+'VT-F11Dm-Mini-Flight-Type-600x599.jpg',
           _JN_BASE+'VT-F11Dm-Mini-Flight-Type.jpg' ],
    img:  _JN_BASE+'VT-F11Dm-Mini-Flight-Type-600x599.jpg',
    tagline:'Compact conveyor dishwasher — continuous uninterrupted washing during peak service with mini-flight footprint.',
    features:[
      'Continuous conveyor — no loading downtime',
      'Mini-flight compact footprint',
      'HACCP auto-dose chemical system',
      'SUS304 stainless steel construction',
      'Low water and chemical consumption',
      'Available for rental or purchase'
    ],
    specs:{ 'Type':'Mini Flight Conveyor', 'Material':'SUS304 Stainless Steel',
            'Chemical Dosing':'Auto HACCP dose', 'Power Supply':'380 V / 50 Hz / 3-phase',
            'Rinse Temperature':'85°C heat sanitise' },
    uses:['Mid-size hotel restaurants','Canteens','Catering operations','Healthcare facilities'] },

  { id:'VTF21DM', brand:'JR-Chem', slug:'jrchem', name:'VTF21DM',
    cat:'Flight Type Dishwasher', tag:'Full Flight',
    imgs:[ _JN_BASE+'11-VT-F21DM-1-600x270.jpg',
           _JN_BASE+'11-VT-F21DM-1.jpg',
           _JN_BASE+'11-VT-F21DM.jpg',
           _JN_BASE+'Special-Process-Wash-Arm-Set-300x278.jpg',
           _JN_BASE+'Strainer-Design-Easy-To-Clean-300x278.jpg',
           _JN_BASE+'Noozle-Design-with-Wide-Angle-Water-Jet-Type-300x278.jpg' ],
    img:  _JN_BASE+'11-VT-F21DM-1-600x270.jpg',
    tagline:'Full flight conveyor — up to 5,000 plates per hour, 2-tank + 1-rinse, for the highest-volume operations.',
    features:[
      'New design wash arm — easy to dismantle and clean',
      'High-efficiency wash pump with full stainless steel impeller',
      'Wide-angle water jet nozzle for thorough coverage',
      'Double-layer door to prevent heat loss and save energy',
      'Washing capacity up to 1,000–5,000 plates/hr via frequency controller',
      'Full SUS304 stainless steel construction'
    ],
    specs:{ 'Dimension':'3855 × 830 × 1650 mm', 'Loading Height':'530 × 420 mm',
            'Capacity':'2.0–3.0 m/min @ 360 racks/hr', 'Rinse Usage':'5 L/min',
            'Wash Pump Power':'1.5 kW', 'Wash Tank Heater':'12 kW + 12 kW', 'Booster Heater':'36 kW',
            'Conveyor Motor':'0.5 kW', 'Power Supply':'380 V / 50 Hz / 3-phase', 'Steam Supply':'90 kg/hr' },
    uses:['Hotel all-day dining','Hospital bulk catering','Airline catering kitchens','Stadium concessions'] },

  /* ══════════════════ Tamago ══════════════════ */
  { id:'TC-100', brand:'Tamago', slug:'tamago', name:'TC-100 (4-Door Upright)',
    cat:'Food Serving Equipment', tag:'4-Door Upright',
    imgs:[ 'https://jrtech.com.my/wp-content/uploads/2022/08/4-Door-Upright-600x599.jpg',
           'https://jrtech.com.my/wp-content/uploads/2022/08/4-Door-Upright.jpg',
           'https://jrtech.com.my/wp-content/uploads/2022/08/Drawer-Counter-Chiller-300x300.jpg' ],
    img:  'https://jrtech.com.my/wp-content/uploads/2022/08/4-Door-Upright-600x599.jpg',
    tagline:'4-door upright food service station — temperature-controlled zones for hotel buffets and patient meal service.',
    features:[
      '4-door upright configuration',
      'Hot & cold zone options',
      'Temperature-controlled food holding',
      'Hotel buffet line optimised design',
      'Easy-clean stainless steel interior',
      'Energy-efficient insulation',
      'Full spare parts support'
    ],
    specs:{ 'Model':'TC-100 / MDS 1040HRF1', 'Configuration':'4-door upright',
            'Application':'Buffet / patient meal service', 'Material':'SUS304 Stainless Steel',
            'Power Supply':'220 V single-phase' },
    uses:['Hotel buffet service','Hospital patient meal service','Institutional cafeteria','Event catering'] },

  { id:'TC-50', brand:'Tamago', slug:'tamago', name:'TC-50 (Drawer Counter Chiller)',
    cat:'Food Serving Equipment', tag:'Counter Chiller',
    imgs:[ 'https://jrtech.com.my/wp-content/uploads/2022/08/Drawer-Counter-Chiller-600x599.jpg',
           'https://jrtech.com.my/wp-content/uploads/2022/08/Drawer-Counter-Chiller.jpg',
           'https://jrtech.com.my/wp-content/uploads/2022/08/4-Door-Upright-300x300.jpg' ],
    img:  'https://jrtech.com.my/wp-content/uploads/2022/08/Drawer-Counter-Chiller-600x599.jpg',
    tagline:'Drawer-style counter chiller — front-of-house chilled food presentation at safe holding temperatures.',
    features:[
      'Drawer-style counter configuration',
      'Precision chiller temperature control',
      'Front-of-house aesthetic design',
      'Easy-access drawer for service staff',
      'Safe food holding compliance',
      'SUS304 hygienic interior',
      'Low-energy compressor system'
    ],
    specs:{ 'Width':'20.3 cm', 'Length':'33.7 cm', 'Height':'30 cm', 'Weight':'5 kg',
            'Water Capacity':'7 litres', 'Temperature Range':'2 – 8°C', 'Power Supply':'220 V single-phase' },
    uses:['Hotel buffet counters','Restaurant service counters','Hospital meal stations','Banquet serving lines'] }
];

/* Helper: find by ID */
function JRT_findProduct(id) {
  for (var i = 0; i < JRT_PRODUCTS.length; i++) {
    if (JRT_PRODUCTS[i].id === id) return JRT_PRODUCTS[i];
  }
  return null;
}

/* Helper: related products (same brand, excluding self, up to limit) */
function JRT_related(product, limit) {
  limit = limit || 4;
  var out = [];
  for (var i = 0; i < JRT_PRODUCTS.length; i++) {
    var p = JRT_PRODUCTS[i];
    if (p.slug === product.slug && p.id !== product.id) {
      out.push(p);
      if (out.length >= limit) break;
    }
  }
  return out;
}
